name: Docker Image CI

on:
    create:
        tags:
            - '*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Get Tag Name
              id: tag
              run: echo ::set-output name=tagname::${GITHUB_REF#refs/tags/}

            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: seeleclover/smartclassroom:service-api-${{ steps.tag.outputs.tagname }}
